# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5652e6793770f3e7702c6574b2195baf6f31fb41820e12514f75ceb7c61c0faa979cb055fc0f3c3f95752c6898bb3eda7d10a6f93b893cd4878cb2dc3f400a34

test:
  secret_key_base: c9b74bbf82ab3936c9f60ebf545f847bc6df92a7ce423a8a0ea19db3e4aa019280aa6003e523ebf118f6755990ae8f602428938e644ff30b81922b17abadbc27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
